######################################################################
# Automatically generated by qmake (2.01a) pon. maj 30 22:57:00 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT += sql network

# Input
HEADERS += IotServer.h Logger.h Listener.h Creator.h
SOURCES += Logger.cpp main.cpp
